openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /start_container:
    get:
      summary: Start Vul Container
      description: |-
        通过应用名称或cve编号启动有漏洞容器,返回容器的url和id信息
        return:
            - code: 0表示成功，1表示失败
            - message: 返回的信息
            - container_info: 容器启动的ip和端口信息和容器id
      operationId: start_vul_container_start_container_get
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulInfo'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /start_base_app_container:
    get:
      summary: Start Base App Container
      description: |-
        通过应用名称和版本号获取基础容器的docker-compose.yml文件
        return:
            - code: 0表示成功，1表示失败
            - message: 返回的信息
            - container_info: 容器启动的ip和端口信息和容器id
      operationId: start_base_app_container_start_base_app_container_get
      parameters:
        - name: app_name
          in: query
          required: true
          schema:
            type: string
            title: App Name
        - name: version
          in: query
          required: false
          schema:
            type: string
            title: Version
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /stop_container:
    get:
      summary: Stop Container
      description: |-
        通过容器id停止容器
        return:
            - code: 0表示成功，1表示失败
            - message: 返回的信息
      operationId: stop_container_stop_container_get
      parameters:
        - name: container_id
          in: query
          required: true
          schema:
            type: string
            title: Container Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /get_vul_doc:
    get:
      summary: Get Vul Doc
      description: |-
        通过应用名称或cve编号获取漏洞文档
        return:
            - code: 0表示成功，1表示失败
            - message: 返回的信息
            - vul_doc: 漏洞验证文档url
      operationId: get_vul_doc_get_vul_doc_get
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulInfo'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
    VulInfo:
      properties:
        app_name:
          type: string
          title: App Name
        cve_id:
          type: string
          title: Cve Id
      type: object
      title: VulInfo
      description: |2-

            漏洞信息模型

            - app_name: 应用名称
            - cve_id: 漏洞编号或具体漏洞名称
            
